# Generated by Django 4.1.3 on 2023-01-12 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='level',
            field=models.ForeignKey(default='Easy', on_delete=django.db.models.deletion.CASCADE, to='quiz_app.level'),
        ),
    ]
