# Generated by Django 4.1.3 on 2023-01-12 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_alter_paper_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.level'),
        ),
    ]
