# Generated by Django 4.1.3 on 2023-01-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_alter_paper_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='level',
        ),
    ]
