# Generated by Django 4.1.3 on 2022-12-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_profile',
            name='profile_pic',
        ),
    ]
