# Generated by Django 4.1.3 on 2022-12-21 13:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_remove_student_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default=2, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
