# Generated by Django 4.1.3 on 2022-12-22 09:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_student_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('Program', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('upload_by', models.CharField(max_length=255)),
            ],
        ),
    ]
