# Generated by Django 4.1.3 on 2022-12-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_comment_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
