# Generated by Django 4.1.5 on 2023-01-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_alter_comment_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_question',
            name='permission',
            field=models.BooleanField(default=False),
        ),
    ]
